### ISSUE TITLE
Detangle serial shell debug output from bootloader implementation

### ISSUE THREAD

**Issue by heliochronix** [oresat/oresat-firmware#48]
Serial debug output is currently baked into bootloader code. This should be detangled from it either via preprocessor switches or completely via a test library for serial shell.

**Comment by ThirteenFish** [comment]
This is done via defining `DEBUG_PRINT` at compile time, typically by passing `-DDEBUG_PRINT` to gcc. The ChibiOS makefile template lets the user put this in `UDEFS`.

Note that this does not disable all serial output because Andrew "likes it when something is on the screen". It'll output a minimal amount of messages at startup and CAN TX/RX.
